version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${username}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${password}
      - DOCKER_INFLUXDB_INIT_ORG=FSP-Cup
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${token}
      - DOCKER_INFLUXDB_HOST=influxdb
    ports:
      - "8086:8086"
  

  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://localhost:8086
      - INFLUXDB_TOKEN=${token}
      - INFLUXDB_ORG=FSP-Cup
      - INFLUXDB_BUCKET=metrics

volumes:
  influxdb_data: